# syntax=docker/dockerfile:1.6

FROM node:20-alpine

WORKDIR /app

ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1
ENV npm_config_legacy_peer_deps=true

RUN apk add --no-cache python3 make g++

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY docker/scripts ./docker/scripts
RUN chmod +x ./docker/scripts/docker-entrypoint.sh

EXPOSE 3000

ENTRYPOINT ["./docker/scripts/docker-entrypoint.sh"]
CMD ["npm", "run", "dev", "--", "-H", "0.0.0.0"]
